version: "3"
services:
  db:
    build: .
    image: oracle-database:11.2.0.2-xe
    container_name: db-oracle11g
    shm_size: 1g
    ports:
      - 1521:1521
      - 8081:8080
    environment:
      ORACLE_PWD: passwd
    volumes:
      - ./db/oradata:/u01/app/oracle/oradata
      - ./db/setup:/docker-entrypoint-initdb.d/setup
